trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: BUILD
  jobs:
  - template: adf-build-job.yml
    parameters:
      subscriptionId: * * * *
      resourceGroupName: * * * *
      dataFactoryName: adf-CItestCD-dev
      repoRootFolder: /data-factory/
      packageJsonFolder: /devops/

- stage: DEV
  variables:
  - group: DEV
  jobs:
  - template: adf-deploy-job.yml
    parameters:
      environmentName: DEV
      subscriptionId: * * * *
      resourceGroupName: * * * *
      dataFactoryName: adf-CItestCD-dev
      serviceConnectionName: testing-sp-data-factory-cicd-dev
      overrideParameters: >
        -LS_AzBlob_connectionString $(BlobConnectionString)
